name: Artifact Signing & SLSA Stage 1 Provenance

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

#This workflow is designed to:
#1. Build Docker image
#2. Sign the Docker image with Cosign
#3. Transparency log the signature to Rekor

#environment variable for the Docker registry and image name
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert image name to lowercase
      id: lowercase
      run: |
        # Convert IMAGE_NAME to lowercase and set it as an output variable
        echo "image=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Build image
      run: |
        docker build -t $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }} -t $REGISTRY/${{ steps.lowercase.outputs.image }}:latest . 
        #the t flag is used to tag the image with both the commit SHA and the latest tag, allowing for versioning and easy reference to the most recent build.
        #steps.lowercase.outputs.image is used to reference the lowercase image name generated in the previous step, ensuring consistency in naming conventions.

    - name: Push image
      run: |
        docker push $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }}
        docker push $REGISTRY/${{ steps.lowercase.outputs.image }}:latest
        #docker push to registry with both commit SHA and latest tag, ensuring the image is available for deployment and version tracking.

    - name: Capture immutable image digest
      id: digest
      run: |
        IMAGE_DIGEST=$(docker inspect \
          $REGISTRY/${{ steps.lowercase.outputs.image }}:${{ github.sha }} \
          --format='{{index .RepoDigests 0}}')

        echo "image_digest=$IMAGE_DIGEST" >> $GITHUB_OUTPUT

        #display the cpatured image digest for verification and logging purposes, ensuring that the exact version of the image can be referenced in future steps or audits.

    - name: Display artifact identity
      run: |
        echo "Artifact:"
        echo "${{ steps.digest.outputs.image_digest }}"

    #sign 
    - name: Sign Docker image with Cosign
      #cosign with keyless signing 
      run: |
        cosign sign --yes "${{ steps.digest.outputs.image_digest }}"
      env:
        #env is for setting environment variables for the step, allowing for secure access to secrets and configuration needed for signing.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

    - name: Verify signature and report to Rekor
      run: |
        cosign verify \
        --certificate-identity-regexp "https://github.com/Mikeyogada/Provenance/.github/workflows/prov_trust.yml@refs/heads/main" \
        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
        "${{ steps.digest.outputs.image_digest }}"

        echo "✓ Signature verified"
        echo "✓ GitHub OIDC identity verified"
        echo "✓ Fulcio certificate validated"
        echo "✓ Rekor transparency log inclusion verified"

    #cosign verify, checks:
    #1. Signature
    #2. Fulcio certificate 
    #3. certificate chain
    #4. Rekor transparency log inclusion
    #5. OIDC identity 
    - name: Generate provenance statement
      run: |
        cat > provenance.json <<EOF
        {
          "_type": "https://in-toto.io/Statement/v1",
          "subject": [
            {
              "name": "${{ steps.digest.outputs.image_digest }}"
            }
          ],
          "predicateType": "https://slsa.dev/provenance/v1",
          "predicate": {

            "builder": {
              "id": "https://github.com/${{ github.repository }}"
            },

            "buildType": "https://github.com/Actions",

            "buildConfig": {
              "workflow": "${{ github.workflow }}",
              "workflow_file": ".github/workflows/provenance-trust.yml"
            },

            "source": {
              "repository": "https://github.com/${{ github.repository }}",
              "branch": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}"
            },

            "runner": {
              "os": "${{ runner.os }}"
            },

            "metadata": {
              "buildStarted": "${{ github.run_id }}",
              "actor": "${{ github.actor }}"
            }

          }
        }
        EOF

    - name: Display provenance
      run: |
        cat provenance.json

    - name: Attach Provenance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cosign attest --yes --predicate provenance.json --type custom "${{ steps.digest.outputs.image_digest }}"

    - name: Verify Provenance
      run: |
        cosign verify-attestation \
          --type custom \
          --certificate-identity-regexp "https://github.com/Mikeyogada/Provenance/.github/workflows/prov_trust.yml@refs/heads/main" \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          "${{ steps.digest.outputs.image_digest }}"

    - name: Display attestation
      run: |
        cosign verify-attestation --type custom "${{ steps.digest.outputs.image_digest }}" --output json 
